import enums.LocationType;
import enums.RoadType;
import enums.RouteOptimization;
import model.*;

import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Generates large random instances of the Best Route Problem and measures
 * the runtime and heap memory consumption of the Dijkstra implementation.
 *
 * <h3>Methodology</h3>
 * <ul>
 *   <li>Locations are randomly distributed in a 10,000 x 10,000 unit coordinate grid.</li>
 *   <li>Each location is randomly assigned a type (City, Airport, GasStation) and
 *       a type-appropriate unique property.</li>
 *   <li>Routes are generated by connecting a random subset of location pairs.
 *       Edge density is configurable via {@code routeMultiplier}.</li>
 *   <li>Connectivity: to guarantee a path always exists, locations are first
 *       linked in a spanning chain (index i to i+1). Additional random edges
 *       are added on top.</li>
 *   <li>IDs are assigned sequentially from 0, which is required for correct
 *       behavior of Dijkstra's ID-keyed data structures.</li>
 * </ul>
 *
 * <h3>Hot-spots identified by analysis</h3>
 * <ol>
 *   <li><b>buildAdjacencyList()</b> in {@link model.Problem} iterates all routes
 *       to build neighbor lists on every call. For repeated queries over the same
 *       graph, caching this structure would eliminate O(E) work per query.</li>
 *   <li><b>PriorityQueue re-insertions</b>: Dijkstra uses lazy deletion (stale
 *       entries remain in the queue). With dense random graphs (E >> V) the queue
 *       can grow to O(E) entries. A decrease-key heap (Fibonacci heap) would reduce
 *       this but Java provides none in stdlib.</li>
 *   <li><b>addLocation / addRoute duplicate checks</b> are O(n) linear scans.
 *       For large N, replacing {@code List} with a {@code LinkedHashSet} and
 *       implementing {@code hashCode} on {@link model.Location} and {@link model.Road}
 *       would reduce insertion to O(1) amortized.</li>
 *   <li><b>Note on hashCode</b>: {@code Location} and {@code Road} override
 *       {@code equals()} without overriding {@code hashCode()}. This violates the
 *       Java contract and causes incorrect behavior in any {@code HashMap} or
 *       {@code HashSet} keyed on those objects directly. The Dijkstra implementation
 *       avoids this by keying on {@code int} IDs instead.</li>
 * </ol>
 */
public class PerformanceAnalyzer {

    private static final Random RAND = new Random(42);
    private static final int    GRID_SIZE        = 10_000;
    private static final int    SPEED_HIGHWAY    = 130;
    private static final int    SPEED_EXPRESS    = 100;
    private static final int    SPEED_COUNTRY    = 60;

    /**
     * Builds a random {@link Problem} instance with {@code numLocations} locations
     * and approximately {@code numLocations * routeMultiplier} routes.
     *
     * <p>A spanning chain ensures connectivity: location[i] is connected to
     * location[i+1] for all i in [0, numLocations-2]. Additional random edges
     * are appended until the target route count is reached.
     *
     * @param numLocations   Number of location nodes.
     * @param routeMultiplier Routes added = {@code numLocations * routeMultiplier}.
     *                        A value of 2 gives a sparse graph; 10 gives a dense one.
     * @return A fully populated {@link Problem} ready to query.
     */
    public static Problem generateRandom(int numLocations, int routeMultiplier) {
        Problem problem = new Problem();

        List<Location> locs = new ArrayList<>(numLocations);
        for (int i = 0; i < numLocations; i++) {
            int x = RAND.nextInt(GRID_SIZE);
            int y = RAND.nextInt(GRID_SIZE);
            Location loc = randomLocation(i, x, y);
            locs.add(loc);
            problem.addLocation(loc);
        }

        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(PrintStream.nullOutputStream()));

        for (int i = 0; i < numLocations - 1; i++) {
            problem.addRoute(new Route(locs.get(i), locs.get(i + 1),
                    randomRoadType(), randomSpeedLimit()));
        }

        int targetRoutes = numLocations * routeMultiplier;
        int attempts     = 0;
        int maxAttempts  = targetRoutes * 5;
        while (problem.getRoutes().size() < targetRoutes && attempts < maxAttempts) {
            int aIdx = RAND.nextInt(numLocations);
            int bIdx = RAND.nextInt(numLocations);
            if (aIdx != bIdx) {
                problem.addRoute(new Route(locs.get(aIdx), locs.get(bIdx),
                        randomRoadType(), randomSpeedLimit()));
            }
            attempts++;
        }

        System.setOut(originalOut);
        return problem;
    }

    private static Location randomLocation(int id, int x, int y) {
        int type = RAND.nextInt(3);
        return switch (type) {
            case 0 -> new City("City_" + id, LocationType.City, x, y, id,
                    RAND.nextInt(2_000_000) + 1_000);
            case 1 -> new Airport("Airport_" + id, LocationType.Airport, x, y, id,
                    RAND.nextInt(10) + 1);
            default -> new GasStation("GasStation_" + id, LocationType.GasStation, x, y, id,
                    RAND.nextInt(200) + 100);
        };
    }

    private static RoadType randomRoadType() {
        return RoadType.values()[RAND.nextInt(3)];
    }

    private static int randomSpeedLimit() {
        int[] limits = {SPEED_COUNTRY, SPEED_EXPRESS, SPEED_HIGHWAY};
        return limits[RAND.nextInt(limits.length)];
    }


    /**
     * Returns current heap memory in use (bytes).
     * Triggers GC first to reduce noise from unreferenced objects.
     */
    private static long usedHeapBytes() {
        Runtime rt = Runtime.getRuntime();
        rt.gc();
        return rt.totalMemory() - rt.freeMemory();
    }

    /**
     * Runs Dijkstra from the first to the last location in the problem
     * and prints timing + memory results for a single benchmark run.
     *
     * @param problem      The problem instance to query.
     * @param optimization Which optimization criterion to use.
     * @param label        A descriptive label for the output line.
     */
    private static void benchmark(Problem problem, RouteOptimization optimization,
                                  String label) {

        List<Location> locs  = problem.getLocations();
        Location       start = locs.get(0);
        Location       end   = locs.get(locs.size() - 1);

        long heapBefore = usedHeapBytes();
        long t0         = System.nanoTime();

        Solution sol = problem.findBestRoute(start, end, optimization);

        long elapsedNs  = System.nanoTime() - t0;
        long heapAfter  = usedHeapBytes();
        long heapDeltaKB = (heapAfter - heapBefore) / 1024;

        String found = (sol != null)
                ? String.format("%.1f km / %.2f h", sol.getTotalDistanceMeters() / 1000.0,
                sol.getTotalTimeHours())
                : "NO PATH";

        System.out.printf("%-55s | %8.2f ms | heap delta: %+7d KB | result: %s%n",
                label, elapsedNs / 1_000_000.0, heapDeltaKB, found);
    }

    /**
     * Runs the full performance suite over a range of problem sizes and prints
     * a formatted table of results to stdout.
     *
     * <p>To profile hot-spots in a real environment:
     * <ul>
     *   <li><b>IntelliJ IDEA</b>: Run > Profile with async-profiler or Java Flight Recorder.</li>
     *   <li><b>VisualVM</b>: Attach to the JVM process; use CPU sampler and heap profiler.</li>
     *   <li><b>JMH</b>: Wrap each benchmark in a {@code @Benchmark} method for
     *       statistically sound microbenchmarks (eliminates JIT warm-up noise).</li>
     * </ul>
     *
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) {
        System.out.println("=".repeat(100));
        System.out.println("  Best Route Problem - Performance Analysis");
        System.out.println("=".repeat(100));
        System.out.printf("%-55s | %10s | %-22s | %s%n",
                "Scenario", "Time (ms)", "Heap delta", "Result");
        System.out.println("-".repeat(100));

        Problem warmup = generateRandom(50, 3);
        warmup.findBestRoute(warmup.getLocations().get(0),
                warmup.getLocations().get(49),
                RouteOptimization.SHORTEST);

        int[] sizes       = {100, 500, 1_000, 2_500, 5_000, 10_000};
        int[] multipliers = {3, 5};

        for (int multiplier : multipliers) {
            for (int n : sizes) {
                long buildStart = System.nanoTime();
                Problem p = generateRandom(n, multiplier);
                long buildMs  = (System.nanoTime() - buildStart) / 1_000_000;

                String buildLabel = String.format("Build  n=%6d, edges~%7d (x%d)",
                        n, p.getRoutes().size(), multiplier);
                System.out.printf("%-55s | %8d ms | (instance construction)%n",
                        buildLabel, buildMs);

                benchmark(p, RouteOptimization.SHORTEST,
                        String.format("  SHORTEST n=%6d, edges~%7d (x%d)", n, p.getRoutes().size(), multiplier));

                benchmark(p, RouteOptimization.FASTEST,
                        String.format("  FASTEST  n=%6d, edges~%7d (x%d)", n, p.getRoutes().size(), multiplier));
            }
            System.out.println("-".repeat(100));
        }

        System.out.println("\n-- Dense graph stress test (route multiplier = 20) --");
        for (int n : new int[]{500, 1_000, 2_000}) {
            Problem p = generateRandom(n, 20);
            benchmark(p, RouteOptimization.SHORTEST,
                    String.format("  SHORTEST dense n=%5d, edges~%7d", n, p.getRoutes().size()));
            benchmark(p, RouteOptimization.FASTEST,
                    String.format("  FASTEST  dense n=%5d, edges~%7d", n, p.getRoutes().size()));
        }

        System.out.println("=".repeat(100));
        System.out.println("\n=== Profiler Notes ===");
        System.out.println("Hot-spots to investigate with a sampling profiler:");
        System.out.println("  1. Problem.buildAdjacencyList()    - O(E) per query; cache for repeated queries");
        System.out.println("  2. PriorityQueue.poll/offer        - O(E log E) for dense graphs with lazy deletion");
        System.out.println("  3. Problem.addLocation/addRoute    - O(n) linear scan; fix with HashSet + hashCode");
        System.out.println("  4. Instance generation (addRoute)  - O(n * routeMultiplier) with duplicate checks");
        System.out.println("\n=== Bug Notes ===");
        System.out.println("  - Location.hashCode() is not overridden (equals contract violated).");
        System.out.println("    Fix: add hashCode() to Location and Road based on their equality fields.");
        System.out.println("  - Original visited[] was boolean[1000] (ArrayIndexOutOfBoundsException for ID >= 1000).");
        System.out.println("    Fixed: replaced with HashSet<Integer>.");
        System.out.println("  - Route.equals was not symmetric (Route(A,B) != Route(B,A)).");
        System.out.println("    Fixed: addRoute() now checks both orderings.");
    }
}